<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="E053677-VM1" name="Regression Tests" tests="31" failures="9" timestamp="1 Feb 2019 07:29:04 GMT" time="4067.92" errors="0">
  <testcase name="ViewPayableTimeMS" time="94.113" classname="test.cases.TimeandLabour.MSS_ViewPayableTimeTest"/>
  <testcase name="EnterTimeSheetByWeekSelfService" time="85.886" classname="test.cases.TimeandLabour.MSS_ApprovePayableTimeTest"/>
  <testcase name="EnterTimeSheetByWeekSelfService" time="49.871" classname="test.cases.TimeandLabour.ESS_ViewPayableTimeTest"/>
  <testcase name="SearchEmployee" time="55.783" classname="test.cases.YearEnd.YearEndReviewT4SlipTest"/>
  <testcase name="SearchEmployee" time="53.89" classname="test.cases.YearEnd.YearEndAmendCancelSlipTest"/>
  <testcase name="addPerson" time="108.713" classname="test.cases.hr.AddPersonTest">
    <failure type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for visibility of element located by By.id: JOB_JOBCODE$0 (tried for 30 second(s) with 3000 milliseconds interval)">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.id: JOB_JOBCODE$0 (tried for 30 second(s) with 3000 milliseconds interval)
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:303)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
	at utilities.BaseClass.getElementByID(BaseClass.java:139)
	at pages.objects.HR.HR_AddPersonPage.JobCodeTextbox(HR_AddPersonPage.java:138)
	at processes.HR.AddPersonProcess.EnterJobInfomationData(AddPersonProcess.java:249)
	at test.cases.hr.AddPersonTest.addPerson(AddPersonTest.java:64)
Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: JOB_JOBCODE$0
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'E053677-VM1', ip: '172.19.250.238', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_181'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:206)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:202)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
	... 28 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- addPerson -->
  <testcase name="NonSuperUserAccessPrecondition" time="34.211" classname="test.cases.TimeandLabour.CR3864_Security.E148_CR3864_NonS34ManagerAccessPreConditionTest"/>
  <testcase name="NonS34ManagerAccessMSS" time="0.296" classname="test.cases.TimeandLabour.CR3864_Security.E148_CR3864_NonS34ManagerAccessManagerSelfServiceTest">
    <failure type="java.lang.Exception">
      <![CDATA[java.lang.Exception
	at utilities.Utils.takeScreenshot(Utils.java:161)
	at test.cases.TimeandLabour.CR3864_Security.E148_CR3864_NonS34ManagerAccessManagerSelfServiceTest.NonS34ManagerAccessMSS(E148_CR3864_NonS34ManagerAccessManagerSelfServiceTest.java:61)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- NonS34ManagerAccessMSS -->
  <testcase name="NonS34ManagerAccessPrecondition" time="40.076" classname="test.cases.TimeandLabour.CR3864_Security.E148_CR3864_NonSuperUserAccessPreConditionTest"/>
  <testcase name="NonSuperUserAccessMSS" time="19.495" classname="test.cases.TimeandLabour.CR3864_Security.E148_CR3864_NonSuperUserAccessManagerSelfServiceTest"/>
  <testcase name="S34ManagerAccessPrecondition" time="33.761" classname="test.cases.TimeandLabour.CR3864_Security.E148_CR3864_S34ManagerAccessPreConditionTest"/>
  <testcase name="S34ManagerAccessUpdateEmployee" time="62.167" classname="test.cases.TimeandLabour.CR3864_Security.E148_CR3864_S34ManagerAccessUpdateS34ManagerEmployeeTest"/>
  <testcase name="TimeKeeperAccessPreCondition" time="36.248" classname="test.cases.TimeandLabour.CR3864_Security.E148_CR3864_TimekeeperAccessPreConditionTest"/>
  <testcase name="TimekeeperAccessS34UpdateEmployee" time="26.251" classname="test.cases.TimeandLabour.CR3864_Security.E148_CR3864_TimekeeperUserAccessUpdateS34ManagerEmployeeTest"/>
  <testcase name="TLSuperUserAccessPreCondition" time="28.402" classname="test.cases.TimeandLabour.CR3864_Security.E148_CR3864_TLSuperUserAccessPreConditionTest"/>
  <testcase name="TLSuperUserS34AccessUpdateEmployee" time="91.225" classname="test.cases.TimeandLabour.CR3864_Security.E148_CR3864_TLSuperUserAccessUpdateS34ManagerEmployeeTest"/>
  <testcase name="S34ManagerSubmitTimeSheet" time="90.107" classname="test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34ManagerEnterTimeTest"/>
  <testcase name="S34Managerdeleterelation" time="114.388" classname="test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34ManagermanagerdeleteEmployeeRelationSuccessTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at utilities.ExcelUtils.setCellData(ExcelUtils.java:65)
	at test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34ManagermanagerdeleteEmployeeRelationSuccessTest.S34Managerdeleterelation(E148_CR3864_S34ManagermanagerdeleteEmployeeRelationSuccessTest.java:42)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- S34Managerdeleterelation -->
  <testcase name="S34ManagerWithMultilpeEmployee" time="321.884" classname="test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34ManagerSelectEmployeeWithUnapprovedTimeTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at utilities.ExcelUtils.setCellData(ExcelUtils.java:65)
	at test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34ManagerSelectEmployeeWithUnapprovedTimeTest.S34ManagerWithMultilpeEmployee(E148_CR3864_S34ManagerSelectEmployeeWithUnapprovedTimeTest.java:51)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- S34ManagerWithMultilpeEmployee -->
  <testcase name="S34Managerdeleterelation" time="76.157" classname="test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34ManagermanagerdeleteEmployeeRelationErrorTest"/>
  <testcase name="TLSuperUserEmp_S34Relationship" time="298.617" classname="test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_TLSuperUserCreateEmpS34ManagerRelationshipTest">
    <failure type="java.lang.AssertionError" message="******Validation Fail Select Employee Page displayed  *****">
      <![CDATA[java.lang.AssertionError: ******Validation Fail Select Employee Page displayed  *****
	at processes.TimeandLabour.ManagerSelfService_UpdateS34ManagerEmployeeProcess.TLSuperUserUpdateEmployee(ManagerSelfService_UpdateS34ManagerEmployeeProcess.java:66)
	at test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_TLSuperUserCreateEmpS34ManagerRelationshipTest.TLSuperUserEmp_S34Relationship(E148_CR3864_TLSuperUserCreateEmpS34ManagerRelationshipTest.java:54)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TLSuperUserEmp_S34Relationship -->
  <testcase name="S34ManagerSelectionDate" time="81.994" classname="test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34ManagerEndDateGraterThenMaxSelectionDateErrorTest"/>
  <testcase name="S34ManagerWithDiffrentOPRID" time="135.097" classname="test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34ManagerDeletRelationshipwithDiffrentOPRIDTest"/>
  <testcase name="S34ManagerSelectOneEmployeeExistingRelation" time="127.532" classname="test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34ManagerCreateRelationshipwithExistingRowinPW_S34_EMPL_MGRTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at utilities.ExcelUtils.setCellData(ExcelUtils.java:65)
	at test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34ManagerCreateRelationshipwithExistingRowinPW_S34_EMPL_MGRTest.S34ManagerSelectOneEmployeeExistingRelation(E148_CR3864_S34ManagerCreateRelationshipwithExistingRowinPW_S34_EMPL_MGRTest.java:44)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- S34ManagerSelectOneEmployeeExistingRelation -->
  <testcase name="S34ManagerSelectOneEmployee" time="258.038" classname="test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34Manager1BUSelectonly1EmployeeTest"/>
  <testcase name="S34ManagerWithMultilpeEmployee" time="246.603" classname="test.cases.TimeandLabour.CR3864_Functional.E148_CR3864_S34Manager1BUCreateRelationEmployeeWithMultipleRecordTest"/>
  <testcase name="EnterTimeToCreateException" time="316.814" classname="test.cases.TimeandLabour.Create_exceptionPWTLX001_FT_Exception_37_5_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at utilities.ExcelUtils.setCellData(ExcelUtils.java:65)
	at test.cases.TimeandLabour.Create_exceptionPWTLX001_FT_Exception_37_5_Test.EnterTimeToCreateException(Create_exceptionPWTLX001_FT_Exception_37_5_Test.java:60)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- EnterTimeToCreateException -->
  <testcase name="EnterTimeToCreateException" time="182.61" classname="test.cases.TimeandLabour.Create_exceptionPWTLX001_FT_Positive_37_5_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at utilities.ExcelUtils.setCellData(ExcelUtils.java:65)
	at test.cases.TimeandLabour.Create_exceptionPWTLX001_FT_Positive_37_5_Test.EnterTimeToCreateException(Create_exceptionPWTLX001_FT_Positive_37_5_Test.java:61)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- EnterTimeToCreateException -->
  <testcase name="EnterTimeToCreateException" time="119.424" classname="test.cases.TimeandLabour.Create_exceptionPWTLX001_PT_Exception_37_5_Test">
    <failure type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for visibility of element located by By.id: DERIVED_ETEO_SAVE_PB (tried for 30 second(s) with 3000 milliseconds interval)">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.id: DERIVED_ETEO_SAVE_PB (tried for 30 second(s) with 3000 milliseconds interval)
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:303)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
	at utilities.BaseClass.getElementByID(BaseClass.java:139)
	at pages.objects.TL.TL_ManagerSelfService_TimeSheetPage.OK(TL_ManagerSelfService_TimeSheetPage.java:66)
	at processes.TimeandLabour.SelfService_EnterTimeSheetProcess.ExceptionTimeSheet(SelfService_EnterTimeSheetProcess.java:116)
	at test.cases.TimeandLabour.Create_exceptionPWTLX001_PT_Exception_37_5_Test.EnterTimeToCreateException(Create_exceptionPWTLX001_PT_Exception_37_5_Test.java:41)
Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: DERIVED_ETEO_SAVE_PB
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'E053677-VM1', ip: '172.19.250.238', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_181'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:206)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:202)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
	... 28 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- EnterTimeToCreateException -->
  <testcase name="tlConfigUserSearchPW_SCHD_ED_RPT" time="68.911" classname="test.cases.TimeandLabour.CR3999_Functional.E149_083_CR3999_TLConfigRoleUserSearchPW_SCHD_ED_RPT_viaQueryManagerTest"/>
  <testcase name="NonSuperUserAccessMSS" time="13.578" classname="test.cases.TimeandLabour.CR3999_Functional.E149_084_CR3999_UsernotAttachedToTLConfigRoleTest"/>
</testsuite> <!-- Regression Tests -->
